### ISSUE TITLE
menu的高度有点大啊

### ISSUE THREAD

**Issue by derekxia1988** [cweijan/decorate#1]
找了半天找到了这个工程，赞一个，就是menu的高度有点大，不够beautiful😄。看你的源码看了半天，改天自己在本地改改试试。

**Comment by cweijan** [comment]
1.3版本高度降低了一点, 老哥可以试试

**Comment by derekxia1988** [comment]
确实好了些，1.4的窗口化按钮点不了了又:sob:

**Comment by cweijan** [comment]
1.4那里处理的不太好, 需要你先在窗口边缘拖动把窗口缩小, 之后才能窗口化
